architect:
  - h1alexbel
docker:
  image: yegor256/rultor-image:1.18.0
merge:
  script: |-
    npm run ci
deploy:
  script: |-
    echo 'There is no such thing as deploy'
    exit -1
release:
  script: |-
    echo 'There is no such thing as release'
    exit -1
